### ISSUE TITLE
Buffer might be considered to be not modified, with undo involved: "Buffer not modified, not writing!"

### ISSUE THREAD

**Issue by blueyed** [chrisbra/SudoEdit.vim#31]
I have noticed several times already, that `:SudoEdit` says:

> Buffer not modified, not writing!

In that case, the buffer is considered to be not modified by Vim, but in fact it is.

I guess that it has something to do with the &undofile handling, because AFAIK undo is involved.

It happens in cases where I edit a file, save it with SudoEdit, then undo the change and then try to save it again:

TEST CASE:
1. echo 1 > 1
2. vim -u NONE -N -c 'set rtp+=~/.vim/bundle/sudoedit | ru! plugin/SudoEdit.vim | set undofile | exe "norm! r2" | SudoWrite | exe "norm u" | SudoWrite' 1

**Comment by mMontu** [comment]
While testing #42 I noticed this problem (that after SudoWrite, issuing an undo changes the file but it doesn't show as modified and `:update` doesn't writes to the disk nor complain about permissions).

> Indeed its a problem with Sudoedit. it happens, because after writing the buffer, it will be set 'nomodified' (e.g. to be able to :q)

I tried to replace the 'nomodified' by inserting :edit! in several different points, but for some reason it always displays the question about discarding the changes, i.e., for some reason it ignores the '!'.

**Comment by blueyed** [comment]
@chrisbra 
Please consider re-opening the issue.  Or should we create a new one?

**Comment by chrisbra** [comment]
What for? There is no solution. We can remove the :f call, but then someone will complain, that buffer is marked modified after being written. If we keep it, after undoing the modified flag is not changed. I consider this side effect to be less important than the other issue.

**Comment by blueyed** [comment]
It's a bug in Vim after all probably?!
Maybe some combination of usage of hooks and `setl nomodified` could work around it.

**Comment by chrisbra** [comment]
I wouldn't call it a bug and as I said, I don't see a way around it.

**Comment by mMontu** [comment]
@chrisbra I'm aware that your knowledge on Vim is very deep, so if you don't see a workaround them it probably doesn't exist. But I'm curious, do you have any idea why the approach I suggested doesn't works? I thought that reloading the file would set modified flag correctly and still work with undo, if I could get rid of those pesky dialogs.

**Comment by chrisbra** [comment]
@mMontu I don't remember exactly, but there were some issues, that prevented it from working correctly.

**Comment by blueyed** [comment]
We could fix this in Vim after all.
