### ISSUE TITLE
SudoWrite fails to write symlink (silently)

### ISSUE THREAD

**Issue by blueyed** [chrisbra/SudoEdit.vim#40]
`SudoWrite` does not work with symlinks:

```
% echo foo > foo
% sudo chown root foo
% ln -s foo symlink
% vim -c 'norm o2' -c 'SudoWrite' -c q symlink
% cat foo
foo
```

The expected result would be to have "2" after "foo".

**Comment by chrisbra** [comment]
What happened to the symlinked file?

**Comment by blueyed** [comment]
It stays intact, so after all the changes are more or less lost.
I have not checked the undofile etc.

**Comment by chrisbra** [comment]
BTW: I could not reproduce your issue. For me, it worked as expected, updating the file to which the symlink points to. This might be an issue with the shell, however.

**Comment by blueyed** [comment]
Sorry, I was using `SudoWrite` from https://github.com/tpope/vim-eunuch accidentally.

**Comment by chrisbra** [comment]
That is kind of funny.
