### ISSUE TITLE
Requires password twice

### ISSUE THREAD

**Issue by mMontu** [chrisbra/SudoEdit.vim#41]
First of all, thanks for sharing this great plugin! It is far better than using the following,

`cabbr w!! w !sudo tee > /dev/null %`

, as it is not OS dependent, far easier to remember and very well documented.

I've just found it on [a vi.stackexchange question](http://vi.stackexchange.com/questions/6637/) and played a little with it (on linux). One point that I noticed is that it asks for the password a second time.
This seems to be caused by the `wundo` call on `<sid>LocalSettings()`.

But I don't understand why it is necessary; using the `cabbr` above asks for the password only once, and it still writes to the undofile (I've tested restarting Vim and it still remembered the changes). If it is for some very specific corner case, do you think it is reasonable to change `s:skip_wundo` to a global variable?

**Comment by chrisbra** [comment]
The problem with the caabr approach is, the undofile will probably written with the wrong permissions, making it impossible for the root user to take advantage of it (especially, if your undodir setting will write it to a different location). I wonder however, why you need to enter the passwords twice. doesn't sudo cache the password for about 15 Minutes? (See timestamp_timeout setting)

**Comment by mMontu** [comment]
I haven't though about the root user to use the undofile, but in my case it wouldn't be possible anyway, as I've configured the undodir inside the regular user home directory.

The sudo timeout is working: if I type a sudo command on the shell twice it indeed asks for the password only once. Maybe the issue is related to the `gnome-ssh-askpass` which the plugin calls imediattely before the second request for password:

```
:!SUDO_ASKPASS='/usr/lib/openssh/gnome-ssh-askpass' sudo -A   sh -c 'test -f '''/home/mmontu/.vim_undodir/%etc%hosts''' && chown 0:0 -- '''/home/mmontu/.vim_undodir/%etc%
hosts''' && chmod a+r -- '''/home/mmontu/.vim_undodir/%etc%hosts''' 2>'/tmp/vxiiCHS/7/error''
```

**Comment by chrisbra** [comment]
hm, perhaps we should make writing the undofile as admin user configurable?

**Comment by mMontu** [comment]
Sounds as a good idea.

**Comment by mMontu** [comment]
I've tried the new version and it still asks for the password twice.

The referenced commit creates as new variable, `s:skip_undo`, but it seems that there is no code checking its value.

**Comment by mMontu** [comment]
It seems that `let s:skip_undo = 1` should be ``let s:skip_wundo = 1`.

**Comment by chrisbra** [comment]
Hi Marcelo!

On Di, 12 Apr 2016, Marcelo D Montu wrote:

> It seems that `let s:skip_undo = 1` should be ``let s:skip_wundo = 1`.

I think you are right. Sorry for that.
