### ISSUE TITLE
`:write another-file` fails after `:SudoWrite`

### ISSUE THREAD

**Issue by blueyed** [chrisbra/SudoEdit.vim#43]
```
TEST CASE:
1. vim /etc/hosts
2. :SudoWrite /tmp/f1
3. :w /tmp/f2

"/tmp/f1" 15L, 298C written
Error occured, when writing undofile
```

It should write `/tmp/f2` instead.

The error related to "undofile" might not be required (I was not seeing it initially).

Ref: https://github.com/chrisbra/SudoEdit.vim/commit/306d3f90064fdafc8e16c499b040ca29403d86f1

**Comment by chrisbra** [comment]
Hm, I am not sure, it is such a good idea to use :w instead of :SudoWrite. Perhaps I should roll back that. (initially, for such cases the sudo:// protocoll handler was supposed to be used).

**Comment by blueyed** [comment]
> Perhaps I should roll back that

Yeah.
It seems to also cause issues with syntax highlighting not being applied anymore after `:w` (but not always?!).  `:syntax on` is required then.

**Comment by blueyed** [comment]
@chrisbra 
I've just run into this issue again, which I consider rather serious.
I've not checked if the target file name would be available in `v:cmdarg` also, but it also would mean that SudoEdit has to handle the optional encoding args that can be in there.

Do you still think it should be rolled back?
Is there another approach to handle #36?

**Comment by chrisbra** [comment]
If you are going to write root files to a different place, you don't need SudoWrite for that. Or is that place also write protected?

**Comment by blueyed** [comment]
> If you are going to write root files to a different place, you don't need SudoWrite for that. Or is that place also write protected?

Usually it is not, but SudoWrite kicks in because of the `BufWriteCmd`.

Thanks for the fix!
