### ISSUE TITLE
Undofile does not work older systems

### ISSUE THREAD

**Issue by aude** [chrisbra/SudoEdit.vim#44]
This problem surfaces when using eg. `let g:sudoAuthArg="-u <user>"`.

Steps to reproduce:

- Run Debian 7 (wheezy).
- Run VIM 7.3 with patches <=547 installed.
  - Tested with `VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 10 2013 02:28:47)`
- `.vimrc`:
  - `set undofile`
  - `set undodir=~/.vim/undo`
  - SudoEdit.vim installed
- `sudo -u vim /tmp/test`
  - Write a test file
- `vim /tmp/test`
  - `:let g:sudoAuth="sudo"`
  - `:let g:sudoAuthArg="-u nobody"`
  - `:SudoWrite`

Now you have lost your undo. You can verify it by writing more and closing and opening the file, you won't get the undo.

Not sure what causes this. Will be happy to help debugging and testing.

**Comment by chrisbra** [comment]
this only happens with older Vims? It does not happen with a recent 7.4.1800 Vim?

**Comment by aude** [comment]
This did not happen with the recent `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  8 2016 14:12:43)` `1-1718` at an up-to-date Fedora installation.
Notably, it also did not happen on Debian 7 (wheezy) with 'VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 11 2014 03:14:29)` `1-488`.

**Comment by chrisbra** [comment]
sounds like a problem that has been fixed with a vim patch. Hm, possibly [7.4.024](https://github.com/vim/vim/releases/tag/v7.4.024). There is nothing I can do against it in the plugin, I am sorry.

**Comment by aude** [comment]
Ah, that sounds plausible.

Just to make sure I have made clear what I can:

- This _does_ work without `-u nobody`. So writing as root makes the undofile accessible. This baffles me, as the file is correctly written, and I did not think the undofile was read through `sudoAuth`.

To add another step to the reproduce steps in the first comment:

- `sudo chown nobody ~/.vim/undo/%tmp%test`

The undofile now works as expected.

**Comment by chrisbra** [comment]
hm, let me think about it a little bit. Perhaps, if `-u` is used, we need an additional call to `sudo chown undofile`? Could that work perhaps?

**Comment by aude** [comment]
No,

**Comment by aude** [comment]
Yeah, the undofile works when the undofile is owned by the same user as the file being edited. But not when the undofile is owned by the current user. Though, that works in recent versions.

The Vim patch you mentioned, [7.4.024](/vim/vim/releases/tag/v7.4.024), does fix that. I'd vote against a workaround and for a Vim update.

**Comment by chrisbra** [comment]
okay, closing then.
