### ISSUE TITLE
Filenames containing spaces generate spurious error messages

### ISSUE THREAD

**Issue by p--b** [chrisbra/SudoEdit.vim#47]
I know filenames containing spaces are a terrible idea, but alas sometimes software from non-UNIX backgrounds ships with them by default. Whilst attempting to :SudoWrite a file whose filename contains spaces, I receive the following error:

```
verb try | undojoin | catch /^Vim\%((\a\+)\)\=:E790/ | endtry | 1,12w !SUDO_ASKPASS='/usr/bin/ksshaskpass' sudo -A  tee >/dev/null  '/opt/ti/Code Composer Studio 7.4.0.desktop'
Error detected while processing function SudoEdit#SudoDo[46]..<SNR>163_LocalSettings:
line  114:
E172: Only one file name allowed: edit Code Composer Studio 7.4.0.desktop
```

Which looks like the extension is misinterpreting a filename with spaces as multiple seperate filenames, unless I'm doing something else wrong? Thanks!

EDIT: Remove spurious errors in debug log.

**Comment by p--b** [comment]
It's worth noting that the file does appear to be written succesfully, just with the above-mentiioned error being emitted also.

**Comment by chrisbra** [comment]
Opps. sorry, did not see this message and did not get a notification from github for it. Sorry for the inconvenience.

Let me fix this quickly.

Thanks for the report and please try current head.
