### ISSUE TITLE
Having a BufReadPre autocommand scrolls other windows on ":edit"

### ISSUE THREAD

**Issue by blueyed** [chrisbra/SudoEdit.vim#56]
```vim
autocmd BufReadPre * echom 'AU'

function! Test()
  call append(0, range(100))
  exe 'w' tempname()
  normal! 50gg
  split
  normal! 100gg
  " edit
endfunction
```

When calling `edit` at the end of the test setup (or manually) will scroll the buffer in the other window to the top.

This does not happen without the BufReadPre autocommand.

**Comment by blueyed** [comment]
Meant for Vim: https://github.com/vim/vim/issues/4294

**Comment by chrisbra** [comment]
yeah, looks like a Vim issue. I'll have a look over there.
