### ISSUE TITLE
Suggestions: remove editing read-only warning, do SudoWrite when saving

### ISSUE THREAD

**Issue by TamaMcGlinn** [chrisbra/SudoEdit.vim#63]
I added this to my vimrc, the result is that I no longer get that annoying warning when editing a file where I don't have the correct permissions, and also that my normal write binding automatically calls SudoWrite (mine is `nnoremap <leader>fw :set buftype=""<CR>:write!<CR>` - we may want to make this work for just regular `:w`). My suggestion is to include this in SudoEdit.

```vimscript
augroup SudoWriteReadOnly
  autocmd FileChangedRO * set noreadonly | execute "autocmd BufWriteCmd <buffer> SudoWrite"
augroup END
```

**Comment by chrisbra** [comment]
thanks. Can you create a PR for that?
